### ISSUE TITLE
Support to MK2

### ISSUE THREAD

**Issue by rafael3r** [tumb1er/BetterBatteryWidget#37]
Hi,

Firstly congratulations for excellent app, the best battery monitor for Garmin watches. 
I had a Garmin Fenix 6 and works perfectly! But, now I bought a MK2i. Is it possible do an update to support the M2S? 

Best regards,

Rafael Rebouças

**Comment by tumb1er** [comment]
Hello! Which device do you mean exactly? Three names here...

**Comment by rafael3r** [comment]
Hi,

Thanks for reply!
MK2 and MK2i are the same. MK2i have a sonar sensor to diving.  I'm using a
MK2i.

Best regards,

Rafael

Em seg., 31 de jan. de 2022 17:24, Sergey Tikhonov ***@***.***>
escreveu:

**Comment by tumb1er** [comment]
It's done already, waiting for public release

**Comment by tumb1er** [comment]
@rafael3r 1.0.0 published to CIQ Store.

**Comment by rafael3r** [comment]
Thank very much!
 I'll check it.

Em ter., 1 de fev. de 2022 07:34, Sergey Tikhonov ***@***.***>
escreveu:
